### ISSUE TITLE
Bloqueio dominio Sicredi

### ISSUE THREAD

**Issue by kernelkill** [openctibr/threatFeeds#1]
Olá;
Estamos usando o repositório de ThreatFeeds em nossos firewalls, e da semana passada pra cá começamos a ter bloqueio no banco sicredi, verificando o repositório, detectamos que o domínio encontra na lista, existe a possibilidade de remove-lo?

![image](https://user-images.githubusercontent.com/4819599/170141741-f46572b2-72eb-4b3e-aef1-d12efbe7faaf.png)

Esse bloqueio esta impactando em nossos trabalhos.

**Comment by openctibr** [comment]
Olá, 

Obrigado pelo apontamento. Estamos retirando a maior parte destes itens de nosso Banco de Dados como Falsos positivos. Fica porém nossa sugestão que você mantenha sua própria base de reputação, que pode com certeza se utilizar de nossas informações para que você possa ter maior controle sobre o que são IOCs de Bloqueio (validados) ou IOCs de Monitoração (Suspeitos).

**Comment by kernelkill** [comment]
> Olá,
> 
> Obrigado pelo apontamento. Estamos retirando a maior parte destes itens de nosso Banco de Dados como Falsos positivos. Fica porém nossa sugestão que você mantenha sua própria base de reputação, que pode com certeza se utilizar de nossas informações para que você possa ter maior controle sobre o que são IOCs de Bloqueio (validados) ou IOCs de Monitoração (Suspeitos).

Muito obrigado, acabamos de ativar o threadfeed em nossas politicas e funcionou.
